### ISSUE TITLE
[Day 14] 문자열 내 p와 y의 개수(레벨1) - 2021.03.08 (월)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#15]
https://programmers.co.kr/learn/courses/30/lessons/12916

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-08.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/0308.py

**Comment by yetree** [comment]
https://github.com/yetree/ps/blob/master/programmers/number_of_p_q.py

**Comment by yetree** [comment]
> https://github.com/lhm0421/codetest1/blob/master/0308.py
헉 Counter를 썼는데 더 쉬운 방법이 있네요

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-08.js

**Comment by UniverseHan** [comment]
와 다들 대단 하시네요 ㅋㅋㅋ 이렇게 꾸준히 참여해주시다니 감사합니다. ㅋ

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_08.js
