### ISSUE TITLE
[Day 15] 문자열 내림차순으로 배치하기(레벨1) - 2021.03.09 (화)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#16]
https://programmers.co.kr/learn/courses/30/lessons/12917

문제풀이 블로그: https://universehan.tistory.com/26

**Comment by yetree** [comment]
https://github.com/yetree/ps/blob/master/programmers/sort_string.py

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-09.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-09.js

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/20210309.cpp
