### ISSUE TITLE
[Week 1] 가장 긴 팰린드룸(레벨3) - 2021.03.07 (일) ~ 2021.03.13 (토)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#17]
https://programmers.co.kr/learn/courses/30/lessons/12904

**Comment by UniverseHan** [comment]
https://github.com/daily-coding-test/programmers/pull/18

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/weekly/2020-03-weekly1.py

**Comment by UniverseHan** [comment]
주간 문제 종료.
