### ISSUE TITLE
[Day 16] 문자열 다루기 기본 - 2021.03.10 (수)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#19]
https://programmers.co.kr/learn/courses/30/lessons/12918

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-10.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-10.js

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210310_string.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/210310.java

**Comment by yetree** [comment]
@lundella 저는 문자열 전체를 parseInt(s) 로 변환해서 NaN인지를 체크했습니다! 한글자씩 하는 것 보다 아주 조금 시간을 절약할 수 있을 것 같아요

**Comment by lundella** [comment]
@yetree 말씀하신게 맞는 것 같아서 한번 해봤는데요, 테스트케이스 3, 11번에서 실패나네요..ㅜㅜ
for문을 이렇게만 바꿔봤는데 혹시 어떻게 작성하셨어요? 실패나는 이유를 잘 모르겠네요..;;
```
    let answer = true;
    
    if(s.length === 0) {
        return answer
    } else if(!((s.length === 4) || (s.length === 6))) {
        answer = false;
        return answer;
    }
    
    
    if(isNaN(parseInt(s))) {
        answer = false;
    }
```

**Comment by yetree** [comment]
@lundella 마지막에 isNaN을 체크하고 return하는 부분이 없습니당 ㅎㅎ

**Comment by yetree** [comment]
https://github.com/yetree/ps/blob/master/programmers/string_management_basic.js

**Comment by lundella** [comment]
@yetree 아~ 제가 풀코드를 안써서 리턴이 없었습니다. 문제 원인은 찾았습니다. 프로그래머스에서 다른 분들이 리뷰를 잘 해주셨더라고요.
 isNaN 함수가 지수표기법을 수로 인식해서 테스트에 실패하는 거라고 하네요. 예를 들면 "1e22"를 false로 반환해버립니다. 그래서 문제의 예상답은 false인데 true를 반환하게 되는거죠. 전혀 예상치도 못했는데 이런 테스트 케이스가 있었습니다. 리뷰주셔서 공부가 되었습니다~

**Comment by yetree** [comment]
@lundella 아.. 저도 모르고 있었네요!! 다시보니 제 코드에선 isNaN으로 체크하지않고 기존 값과 비교하도록 체크했었네요. 감사합니다.

**Comment by UniverseHan** [comment]
다들 수고 하셨습니다 :)

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_10.js
