### ISSUE TITLE
[Day 6] 체육복(레벨1) - 2021.02.28

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#2]
https://programmers.co.kr/learn/courses/30/lessons/42862

화이팅

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-02-28.py

**Comment by ezaurum** [comment]
https://github.com/ezaurum/daily-coding-test/blob/main/2021-02-28.js

**Comment by UniverseHan** [comment]
수고하셨습니다.
