### ISSUE TITLE
[Day 17] 서울에서 김서방 찾기(레벨1) - 2021.03.11 (목)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#22]
https://programmers.co.kr/learn/courses/30/lessons/12919

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_11.js

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-11.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-11.js

**Comment by SaeromB** [comment]
https://github.com/SaeromB/daily-coding-test/blob/main/2021-03-11.js

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210311_arr.py

**Comment by yetree** [comment]
https://github.com/yetree/ps/blob/master/programmers/where_is_kim.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/210311.py
