### ISSUE TITLE
[Day 18] 소수 찾기(레벨1) - 2021.03.12 (금)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#23]
https://programmers.co.kr/learn/courses/30/lessons/12921

**Comment by yetree** [comment]
https://github.com/yetree/ps/blob/master/programmers/prime_number.js

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-12.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/210312.py
