### ISSUE TITLE
[Day 19] 수박수박수박수박수박수(레벨1) - 2021.03.13 (토)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#24]
https://programmers.co.kr/learn/courses/30/lessons/12922

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-13.py

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210313.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/210313.py

**Comment by UniverseHan** [comment]
종료

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-13.js

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_13.js
