### ISSUE TITLE
[Day 20] 문자열을 정수로 바꾸기 - 2021.03.14 (일)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#26]
https://programmers.co.kr/learn/courses/30/lessons/12925

**Comment by hjchoi0423** [comment]
해결했습니다!
![Uploading Screenshot_20210315-042802_KakaoTalk.jpg…]()

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-14.py

**Comment by UniverseHan** [comment]
@hjchoi0423 와우 축하해요!!

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-14.js

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_14.js
