### ISSUE TITLE
[Day 22] 내적(레벨1) - 2021.03.16 (화)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#28]
https://programmers.co.kr/learn/courses/30/lessons/70128

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-16.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-16.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/210316.java
