### ISSUE TITLE
[Day 23] 약수의 합(레벨1) - 2021.03.17 (수)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#29]
https://programmers.co.kr/learn/courses/30/lessons/12928

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-17.py

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_17.js

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210317_sum_of_factors.py

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-17.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-17.js

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/03172020.py

**Comment by duckhyunJeung** [comment]
https://github.com/duckhyunJeung/daily-code-test/blob/master/2021-03-17.js

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/0317.py
