### ISSUE TITLE
[Day 7] K번째 수 - 2021.03.01

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#3]
https://programmers.co.kr/learn/courses/30/lessons/42748

화이팅 ㅋ

7번째꺼 풀고 온라인 회식 한번 할까요?

**Comment by UniverseHan** [comment]
2021년 2월 2일 완료

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-01.py

**Comment by ezaurum** [comment]
https://github.com/ezaurum/daily-coding-test/blob/main/2021-03-01.js

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-01.js
