### ISSUE TITLE
[Week 2] [1차] 추석 트래픽(레벨3) - 2021.03.14 (일) ~ 2021.03.20 (토)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#31]
문제 링크 : https://programmers.co.kr/learn/courses/30/lessons/17676

쉽지 않겠지만 한번 해보죠ㅎㅎ

**Comment by ezaurum** [comment]
https://github.com/daily-coding-test/programmers/pull/43

**Comment by UniverseHan** [comment]
고생하셨습니다. ㅋ
