### ISSUE TITLE
[Day 24] 이상한 문자 만들기(레벨1) - 2021.03.18 (목)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#38]
문제 : https://programmers.co.kr/learn/courses/30/lessons/12930

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_18.js

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/20200318.py

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/20210318.py

**Comment by duckhyunJeung** [comment]
https://github.com/duckhyunJeung/daily-code-test/blob/master/2021-03-18.js

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-18.JS

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-18.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-18-%EC%9D%B4%EC%83%81%ED%95%9C%EB%AC%B8%EC%9E%90%EB%A7%8C%EB%93%A4%EA%B8%B0.py
