### ISSUE TITLE
[Day 4] 신규 아이디 추천

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#4]
[문제 - 신규 아이디 추천](https://programmers.co.kr/learn/courses/30/lessons/72410)

[블로그 - 신규 아이디 추천](https://universehan.tistory.com/19?category=929489)

**Comment by UniverseHan** [comment]
석규님 풀이
https://github.com/ezaurum/daily-coding-test/blob/main/2021-02-26.js

**Comment by UniverseHan** [comment]
2021년 2월 26일 금요일 완료

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-02-26.py
