### ISSUE TITLE
[Day 25] 자릿수 더하기(레벨1) - 2021.03.19 (금)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#41]
문제 : https://programmers.co.kr/learn/courses/30/lessons/12931

쉬운 문제이지만 다양한 방법으로 풀어볼 수 있을것 같습니다.
- 내장 라이브러리를 사용하는 방법
- 직접 구현해 보는 방법.

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_19.js

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-19.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-19.js

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/20210319.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-18.py

**Comment by UniverseHan** [comment]
오 다들 꾸준히 하시네요! 고생하셨습니다. ㅋ
