### ISSUE TITLE
[Day 26] 자연수 뒤집어 배열로 만들기 - 2021.03.20 (토)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#48]
문제: https://programmers.co.kr/learn/courses/30/lessons/12932

내장 함수를 이용하면 간단한데. 뒤집는 부분을 직접 한번 구현해 보는것도 재미있을것 같네요.

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-20.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-20.js

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_20.js
