### ISSUE TITLE
[Day 27] 정수 내림차순으로 배치하기 - 2021.03.21 (일) 

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#49]
문제: https://programmers.co.kr/learn/courses/30/lessons/12933

이것도 내장함수 이용하지 않고도 한번 풀어보세요.

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-22.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-21.py

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-21.py
