### ISSUE TITLE
[Day 28] 정수 제곱근 판별 도움말 - 2021.03.22 (월)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#53]
문제: https://programmers.co.kr/learn/courses/30/lessons/12934

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/20210322.py

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-22.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-22.py

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210322.py

**Comment by lhm0421** [comment]
https://github.com/lhm0421/codetest1/blob/master/210322.py

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_22.js

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-22.js
