### ISSUE TITLE
[Day 29] 제일 작은수 제거하기 - 2021.03.22 (화)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#54]
문제: https://programmers.co.kr/learn/courses/30/lessons/12935

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-23.py

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210323.py

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/20210323.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-23.py

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_23.js

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-23.js
