### ISSUE TITLE
[Day 30] 짝수와 홀수(레벨1) - 2021.03.24 (수)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#55]
문제 : https://programmers.co.kr/learn/courses/30/lessons/12937

**Comment by viridis45** [comment]
https://github.com/viridis45/Python_CodingExercise/blob/master/20210324.py

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_24.js

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-24.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-24.js

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-24.py
