### ISSUE TITLE
[Day 31] 키패드 누르기(레벨1) - 2021.03.25 (목) 

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#56]
문제 : https://programmers.co.kr/learn/courses/30/lessons/67256

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-25.py

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-25.py

**Comment by UniverseHan** [comment]
이번 문제는 좀 어려웠나 보군요 ㅋㅋ

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-25.js
