### ISSUE TITLE
[Day32] 최대공약수와 최소공배수(레벨1) - 2021.03.26 (금)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#58]
문제: https://programmers.co.kr/learn/courses/30/lessons/12940

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-26.js

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-26.py
