### ISSUE TITLE
[Day33] 콜라츠 추측(레벨1) - 2021.03.11 (토)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#59]
문제: https://programmers.co.kr/learn/courses/30/lessons/12943

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-27.js

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-27.py
