### ISSUE TITLE
[Day34] 평균 구하기(레벨1) - 2021.03.12 (일)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#60]
문제: https://programmers.co.kr/learn/courses/30/lessons/12944

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-28-%ED%8F%89%EA%B7%A0%EA%B5%AC%ED%95%98%EA%B8%B0.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-28.js
