### ISSUE TITLE
[Day 36] 핸드폰 번호 가리기 - 2021.03.30 (화)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#64]
문제: https://programmers.co.kr/learn/courses/30/lessons/12948

**Comment by hygjob** [comment]
https://github.com/hygjob/solving-algo-daily/blob/main/2021-03-30-%ED%95%B8%EB%93%9C%ED%8F%B0%EB%B2%88%ED%98%B8%EA%B0%80%EB%A6%AC%EA%B8%B0.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-03-30.js

**Comment by prograsshopper** [comment]
https://github.com/prograsshopper/daily-algorithm/blob/main/programmers/20210330.py
