### ISSUE TITLE
[Day 1] 두 개 뽑아서 더하기(레벨1)

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#7]
[문제: 두 개 뽑아서 더하기(프로그래머스)](https://programmers.co.kr/learn/courses/30/lessons/68644)

**Comment by UniverseHan** [comment]
나의 문제 풀이
![image](https://user-images.githubusercontent.com/11917873/109402985-0d7dbf00-7963-11eb-8dc5-d28c8d64b351.png)

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3.js
