### ISSUE TITLE
[Day 42] 비밀지도 - 2021.04.07 (수)

### ISSUE THREAD

**Issue by ezaurum** [daily-coding-test/programmers#72]
https://programmers.co.kr/learn/courses/30/lessons/17681

**Comment by Lagavulin9** [comment]
https://github.com/Lagavulin9/daily_coding_test/blob/main/secret_map.py

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/level1/2021-03-28(4).py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-04-05.js
