### ISSUE TITLE
[Day 43]  실패율 - 2021.04.08 (목)

### ISSUE THREAD

**Issue by ezaurum** [daily-coding-test/programmers#73]
https://programmers.co.kr/learn/courses/30/lessons/42889

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/level1/2021-03-29(2).py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-04-07.js

**Comment by UniverseHan** [comment]
@lundella 님 정말 꾸준히 하시는군요 ㅋㅋ 절실함이 느껴집니다. ㅋㅋ

**Comment by Lagavulin9** [comment]
https://github.com/Lagavulin9/daily_coding_test/blob/main/failure_rate.py
