### ISSUE TITLE
[Day 44] 다트게임 - 2021.04.09 (금)

### ISSUE THREAD

**Issue by ezaurum** [daily-coding-test/programmers#74]
https://programmers.co.kr/learn/courses/30/lessons/17682

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/level1/2021-03-30.py

**Comment by lundella** [comment]
https://github.com/lundella/daily-coding-test/blob/master/2021-04-08.js

**Comment by Lagavulin9** [comment]
https://github.com/Lagavulin9/daily_coding_test/blob/main/dart.py
