### ISSUE TITLE
[Day 8] 2016년 (레벨1) 2021.03.02

### ISSUE THREAD

**Issue by UniverseHan** [daily-coding-test/programmers#9]
- 문제: [2016년 -프로그래머스(레벨1)](https://programmers.co.kr/learn/courses/30/lessons/12901)

**Comment by mathncode** [comment]
https://github.com/mathncode/solving-algo-daily/blob/main/2021-03-02.py

**Comment by ezaurum** [comment]
https://github.com/ezaurum/daily-coding-test/blob/main/2021-03-02.js

**Comment by geunkioh** [comment]
https://github.com/geunkioh/daily-algorithm-test/blob/main/level1_2021_3_2.js
